### PR TITLE
Standardize folder structure to simplify installation non-anaconda users

### PR DESCRIPTION
**Pull request by coldfix**
Hey,

this pull-request introduces a more standard folder structure to simplify installation without anaconda. Basically, the python package is moved to a subdirectory, while all the meta files stay in the parent directory.

This allows automated installation via `python setup.py install/develop/..` or `pip install` in non-anaconda environments, e.g.:

```
# install setup time dependencies first:
pip install numpy matplotlib scipy h5py cython

# now clone and use the package from the working directory:
git clone git@github.com:PyCOMPLETE/PyHEADTAIL
cd PyHEADTAIL
python setup.py develop

# OR directly install from github:
pip install git+git://github.com/PyCOMPLETE/PyHEADTAIL
```

Some comments:
- I don't know about the creation of your anaconda package, I guess you will have to adapt that for the new folder structure.
- Users having installed PyHEADTAIL via the recommended method won't need any `PYTHONPATH` anymore.
- I couldn't find the `hdf5` package on PyPI, but for basic examples it was not needed, in other cases it may still be necessary to install via anaconda (although I didn't do any further research if the hdf5 package can be installed without), so for now I simply commented it out
- I recommend diverting from the dynamic based versioning scheme, and using static [semantic versioning](http://semver.org/) instead, this way, you don't have to assume users having git installed AND users/devs will be able to see the kind of changes between versions. (Just put a static version number in `PyHEADTAIL/_version.py`)
- many of the dependencies are actually setup-time dependencies (because the cython packages depend on them) so I changed the relevant kwarg in `setup.py`. However, this is not sufficient in the case of `numpy` and `cython` because they are already imported before `setup` gets called. There is a way around this with the tradeoff of introducing more complexity in the setup script. If you are interested, I could provide a further patch. You can also see how it's done in [cpymad](https://github.com/hibtc/cpymad/blob/master/setup.py).

I also recommend adding a [PyPI](https://pypi.python.org/pypi) package to further simplify installation, like so:

```bash
# do this once (create an account on PyPI first)
python setup.py register

# for every release
python setup.py sdist
twine upload dist/NAME_OF_THE_RELEASE.tgz
```

After this, users should be able to install PyHEADTAIL without anaconda like so (if they want in an virtualenv):

```
pip install numpy scipy matplotlib h5py cython
pip install PyHEADTAIL
```

### CODE REVIEW

**Comment by coldfix** [comment]
One more comment: This currently does not include the `.html` files generated by cython etc into the installation and does not include the test files in the installation package. Give me a heads up if this should be changed.

**Comment by aoeftiger** [comment]
Hi @coldfix, thanks a lot for your PR! Sorry for the delayed response, I just returned to work. I will go through your proposed changes, sounds great so far!

**Comment by aoeftiger** [comment]
By the way, the cython .html compilations are not required to be part of the installation. 

I'm not sure what you mean by the test files in your last comment.

**Comment by aoeftiger** [comment]
@coldfix can I ask you to rebase versus `develop` instead of `master`? That'd be great. Thanks

**Comment by coldfix** [comment]
Okay, no problem, I will rebase. Can you describe what exactly you want for versioning?

As is, the patch updates the version on each run of `setup.py` rather than each import of the package. The rationale behind this was to remove git as a runtime dependency (which can be particularly bad on windows where you have to take care of PATH first). A setup time dependency on git is IMO still suboptimal but at least not quite as bad.

**Comment by coldfix** [comment]
Oh, I see, you will take care of that, I didn't notice your commit.

**Comment by aoeftiger** [comment]
Cool, thanks!

The idea is to automate our 2-step [release process](https://github.com/PyCOMPLETE/PyHEADTAIL/wiki/Our-Development-Workflow) using e.g. doit. The versioning will then be taken care of even earlier at release time by the developer and never at the user side.

I will look into that next, so for the moment you may leave it as is.

**Comment by coldfix** [comment]
Ok, I rebased and added a few more minor changes which may be useful if you want to release on PyPI. Though, now I have an issue building `PyHEADTAIL/general/errfff.f90`. The error is:

```
building extension "PyHEADTAIL.general.errfff" sources
f2py options: []
f2py:> build/src.linux-x86_64-2.7/PyHEADTAIL/general/errfffmodule.c
Reading fortran codes...
	Reading file 'PyHEADTAIL/general/errfff.f90' (format:fix)
Line #32 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MWFLT = 2, MREAL = 4)                             "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #33 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCWRD = 4)                                        "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #33 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCWRD = 4)                                        "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #34 in PyHEADTAIL/general/errfff.f90:"      PARAMETER         (MCNAM = 16, MWNAM = MCNAM / MCWRD)                "
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Traceback (most recent call last):
  File "setup.py", line 117, in <module>
    ['PyHEADTAIL/general/errfff.f90'])],
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/setuptools/command/develop.py", line 36, in run
    self.install_for_development()
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/develop.py", line 17, in install_for_development
    old_develop.install_for_development(self)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/setuptools/command/develop.py", line 130, in install_for_development
    self.run_command('egg_info')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/egg_info.py", line 18, in run
    self.run_command("build_src")
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 148, in run
    self.build_sources()
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 165, in build_sources
    self.build_extension_sources(ext)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 327, in build_extension_sources
    sources = self.f2py_sources(sources, ext)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/distutils/command/build_src.py", line 564, in f2py_sources
    ['-m', ext_name]+f_sources)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 408, in run_main
    postlist = callcrackfortran(files, options)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/f2py2e.py", line 329, in callcrackfortran
    postlist = crackfortran.crackfortran(files)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 3245, in crackfortran
    readfortrancode(files, crackline)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 511, in readfortrancode
    dowithline(finalline)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 782, in crackline
    analyzeline(m, pat[1], line)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 1188, in analyzeline
    t = determineexprtype(initexpr, params)
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 2971, in determineexprtype
    return _ensure_exprdict(vars[e])
  File "/home/thomas/dev/3rdparty/PyHEADTAIL/.virtualenv/27/lib/python2.7/site-packages/numpy/f2py/crackfortran.py", line 2947, in _ensure_exprdict
    raise AssertionError(repr(r))
AssertionError: ''
```

Didn't have a closer look so far.

Best, Thomas

**Comment by aoeftiger** [comment]
I haven't seen this before, what system are you running on?
This Fortran function has a long history at CERN and predates PyHEADTAIL by decades...

**Comment by coldfix** [comment]
I'm running archlinux, but this seems to be an issue in f2py. Are you using the latest version? (I can check later in more detail)

**Comment by aoeftiger** [comment]
OK, weird... My server versions are 
- f2py 2
- numpy 1.11.3
- gfortran 4.8.4
on Ubuntu 14.04...

**Comment by aoeftiger** [comment]
Usually we use the setup.py to build PyHEADTAIL in place, as the Makefile shows. Can you tell me how you are running it? (The Makefile would need to refer to the relocated thrust.cu as well)

**Comment by coldfix** [comment]
I'm using f2py2 from numpy 1.12.0 on python 2.7.13 in a virtualenv.

I'm building with `python setup.py build` (same with `build_ext --inplace`) directly rather than `make`. Not sure, what's causing the issue.

By the way, one should change the name of the `PyHEADTAIL` target in the makefile or mark it `.PHONY:`, otherwise it won't build now because the directory already exists.

**Comment by aoeftiger** [comment]
Hm I can't reproduce your problem with the fortran so far -- let's see whether this turns up later. All in all it looks good to me now, thanks again for your work!

**Comment by coldfix** [comment]
Thanks. Yes, I don't think this was related to the PR either.

**Comment by aoeftiger** [comment]
Just to follow up on the fortran issue: I ran into a similar compilation problem (upon running the make file i.e. building via build_ext --inplace) where gfortran complains about syntax errors. I resolved it by cleaning the working tree first (make clean). 
Can you try whether this resolves the issue for you as well, @coldfix ?

**Comment by coldfix** [comment]
Did not do the trick for me. I'll open a separate issue, but this has no priority for me.

**Comment by coldfix** [comment]
Nevermind, issue pages are disabled (I guess?). We can keep it here. I'll notify you if I ever have the need to fix this and have some idea how. Sorry for the noise.

**Pull request merged**
