### PR TITLE
Add rectangular gfactor

### PR DESCRIPTION
**Pull request by davidkelliher**
Adding a rectangular pipe expression to the `LongSpaceCharge` class.

### CODE REVIEW

**Comment by aoeftiger** [comment]
For the merge we'd need to rebase your branch against `PyHEADTAIL/develop` (as this is where we typically merge new features). --> `git fetch && git rebase origin/develop` should do if there's no collisions between your code and the latest development status (which I guess is the case). Could you do that @davidkelliher ? Thanks a lot for your contribution!

**Comment by davidkelliher** [comment]
I hope this works! For some reason a bunch of others files changed as well. I hope you can ignore those and just apply the modified spacecharge.py.

**Comment by aoeftiger** [comment]
I've worked your addition into a separate class to be more flexible + faster (since the computation of the effective radius is only done once at instantiation and not for every track call).
Could you check please?

**Comment by aoeftiger** [comment]
Thanks for checking the new version and your feedback by email, @davidkelliher , I'll proceed to merge the slightly adapted version in PR https://github.com/PyCOMPLETE/PyHEADTAIL/pull/141.

**Pull request closed without merging**
